### ISSUE TITLE
SVGView transparency

### ISSUE THREAD

**Issue by tchret** [exyte/Macaw#236]
![image](https://user-images.githubusercontent.com/4539476/33497145-3aaab6ea-d6cd-11e7-8ead-112257cd1926.png)

I don't understand why I have this black bacgkround on my `SVGView`

**logo.svg** 
```
<svg width="66px" height="76px" viewBox="0 0 66 76" version="1.1" >
    <!-- Generator: Sketch 47.1 (45422) - http://www.bohemiancoding.com/sketch -->
    <defs>
        <path d="M32.6238469,0.362657583 L63.32509,18.1388986 L63.32509,18.1388986 C63.7110839,18.3623918 63.9487462,18.7746259 63.9487462,19.2206534 L63.9487462,54.7793466 L63.9487462,54.7793466 C63.9487462,55.2253741 63.7110839,55.6376082 63.32509,55.8611014 L32.6238469,73.6373424 L32.6238469,73.6373424 C32.2364131,73.8616694 31.758593,73.8616694 31.3711592,73.6373424 L0.669916114,55.8611014 L0.669916114,55.8611014 C0.283922239,55.6376082 0.0462599312,55.2253741 0.0462599312,54.7793466 L0.0462599312,19.2206534 L0.0462599312,19.2206534 C0.0462599312,18.7746259 0.283922239,18.3623918 0.669916114,18.1388986 L31.3711592,0.362657583 L31.3711592,0.362657583 C31.758593,0.138330635 32.2364131,0.138330635 32.6238469,0.362657583 Z" id="path-1"></path>
        <path d="M32.6238469,0.362657583 L63.32509,18.1388986 L63.32509,18.1388986 C63.7110839,18.3623918 63.9487462,18.7746259 63.9487462,19.2206534 L63.9487462,54.7793466 L63.9487462,54.7793466 C63.9487462,55.2253741 63.7110839,55.6376082 63.32509,55.8611014 L32.6238469,73.6373424 L32.6238469,73.6373424 C32.2364131,73.8616694 31.758593,73.8616694 31.3711592,73.6373424 L0.669916114,55.8611014 L0.669916114,55.8611014 C0.283922239,55.6376082 0.0462599312,55.2253741 0.0462599312,54.7793466 L0.0462599312,19.2206534 L0.0462599312,19.2206534 C0.0462599312,18.7746259 0.283922239,18.3623918 0.669916114,18.1388986 L31.3711592,0.362657583 L31.3711592,0.362657583 C31.758593,0.138330635 32.2364131,0.138330635 32.6238469,0.362657583 Z" id="path-3"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group-3" transform="translate(1.000000, 1.000000)">
            <mask id="mask-2" fill="white">
                <use xlink:href="#path-1"></use>
            </mask>
            <g id="Polygon-2"></g>
            <mask id="mask-4" fill="white">
                <use xlink:href="#path-3"></use>
            </mask>
            <use id="Polygon-2" stroke="#FFFFFF" xlink:href="#path-3"></use>
            <polygon id="Line-2" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="32.6806228 73.8174446 -0.0570652435 54.8871 -0.557644865 55.7527905 32.1800432 74.6831351"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="8.73822943 26.0322229 0.0489720646 17.7931431 -0.639087275 18.5187975 8.05017009 26.7578773"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="8.06082166 26.7575137 32.7039963 -0.0294491123 31.968054 -0.706493277 7.32487927 26.0804695"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="-0.603963172 55.8718042 32.3693073 63.6524866 32.5989693 62.6792162 -0.374301142 54.8985338"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="32.497487 74.5000007 32.4975038 62.5510211 31.4975038 62.5510197 31.497487 74.4999993"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="0.348281067 56.1139664 8.64533899 25.7002424 7.68059455 25.437054 -0.616463379 55.850778"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="64.5657932 55.8516546 56.3152881 25.4375556 55.3501688 25.6993658 63.6006739 56.1134648"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="64.3239426 54.8984163 31.3959194 62.6794063 31.6258889 63.6526041 64.5539121 55.8716141"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="56.6701269 26.0804693 32.0269366 -0.706493286 31.2909945 -0.0294488872 55.9341847 26.7575137"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="55.9437259 26.7578469 64.6591549 18.5199077 63.9722361 17.7931735 55.2568071 26.0311127"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="7.53137255 26.5510204 56.4636336 26.5510204 56.4636336 25.5510204 7.53137255 25.5510204"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="7.3398915 25.9031896 31.8496722 63.7425015 32.6889841 63.1988512 8.17920338 25.3595394"></polygon>
            <polygon id="Line" fill="#FFFFFF" fill-rule="nonzero" mask="url(#mask-4)" points="32.1453339 63.7425015 56.6551146 25.9031896 55.8158027 25.3595394 31.306022 63.1988512"></polygon>
        </g>
    </g>
</svg>

```

**Comment by ystrot** [comment]
Thank you for reporting. We reproduced this issue and will take a look.

**Comment by ystrot** [comment]
This fix available in the master branch and will be part of 0.9.2 release.

**Comment by loryhuz** [comment]
Hello,

I still have issues with my SVG's, and also tested with the one author has issued in the first place.
I'm linked on master at the current last commit (https://github.com/exyte/Macaw/commit/461dfa869a15797b233466e0c740e4ffab497852)
