### ISSUE TITLE
Memory issue:- CoreAnimation, failed to allocate 13771328 bytes

### ISSUE THREAD

**Issue by Muhammad-AhmadRafique** [exyte/Macaw#476]
Hi everyone, I am using Macaw library for one of my iOS Project,  this library is awesome and contains many features and I have almost completed my app. 
But I am facing a serious issue regarding memory.
**CoreAnimation: failed to allocate 13771328 bytes**
It happens when I load multiple SVG files from memory, and when I go to another screen, the previous files which were loaded into memory, did not remove from memory.
And when user comes to this screen 2 to 3 times, memory issue occurred and app crashes.
Actually I have to create an avatar, so I must load many files into memory at the same time.

Please any help, I will be really grateful to you...!
Kind Regards,
Ahmad

**Comment by amarunko** [comment]
Hi, @Muhammad-AhmadRafique, can you try the last commit of  https://github.com/exyte/Macaw/tree/swift_4.1.x branch? Some memory related issues were fixed after release. Please, give us know if it won't help.

**Comment by Muhammad-AhmadRafique** [comment]
@amarunko , Thank you so much for your reply.
I have updated my 'Macaw' pod with latest commits, but I am still facing the same issue and my app is crashing.
I am sending you my app logs, it may help you to identify the problem

 **[Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
 [Unknown process name] If you want to see the backtrace, please set CG_NUMERICS_SHOW_BACKTRACE environmental variable.
[Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
[process_info] Exiting because our workspace host has disconnected.**

Please help me to resolve this issue, 
Once again, thanks for your help.

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
@Muhammad-AhmadRafique , can you also attach iOS version?

**Comment by Muhammad-AhmadRafique** [comment]
I am running on my app on :-
iPhone device version : 11.4
Xcode version : 9.4

**Comment by amarunko** [comment]
Thanks for additional info. We will look into this issue soon.

**Comment by Muhammad-AhmadRafique** [comment]
Thanks for your help, 
Kindly resolve this issue, so that I can upload my app on Appstore.
I will be waiting for your response.

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
Hi, @Muhammad-AhmadRafique, I checked on memory issues and everything look fine, how do you store views on your controller?

**Comment by Muhammad-AhmadRafique** [comment]
Hi @amarunko , Thanks for your reply...!
For my views, I create different views and the add as a subview to my ViewController in viewDidLoad method and set frame according to their sizes, like below:-

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(topSelectionView)
        view.addSubview(bottomSingleSelectionView)
        view.addSubview(swipeNamesTopView)
        view.addSubview(colorSelectionView)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        topSelectionView.frame = mainView.frame
        bottomSingleSelectionView.frame = mainBottomView.frame
        swipeNamesTopView.frame = swipeNamesView.frame
        colorSelectionView.frame = mainBottomView.frame
        bottomSingleSelectionView.layer.addBorder(edge: .top, color: UIColor.lightGray, thickness: 0.5)
    }

And for view controllers flow, I am using stack, i.e. I push and pop view controller and sometimes using segues to perform it.

Am I doing something wrong ?
Please help...!

Kind Regards,
Mohammad Ahmad

**Comment by Muhammad-AhmadRafique** [comment]
I have a question,
When multiple svg files are loaded in different views like this:-
**View.fileName = "svgName";**

After going to another controller, the previous files which were loaded, remain in the memory ?
Because I checked it, the files do not remove from memory even if we move to other screens. And when we came back to this controller, the files are loaded again and again.
And after 2,3 times, memory issue occur.

Please help...!

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
Hi, @Muhammad-AhmadRafique, looks fine, strange... Did you use storyboards? Your custom views - it is SVGView, MacawView or child views of inherited class from MacawView?

**Comment by Muhammad-AhmadRafique** [comment]
Yes I am using storyboards.
I have created a separate nib file, where almost 20 views are added of custom type SVGView and I use this xib file in my whole project wherever I need.

Actually these 20 views collectively make an avatar view i.e. these are like hairView, faceView, bodyView etc. Thus, creating an avatar.
Please see this screenshot:-  https://cloudup.com/ciFX_cvfe1G

Regards,

**Comment by Muhammad-AhmadRafique** [comment]
Hi @amarunko Thanks for your response,
Actually I am using only one xib file created only for svgViews which I sent you, in my whole app wherever I want.
But in my viewControllers, to separate core functionality based on different features, I created separate views and add as subviews to my ViewController (these views are not related to svgViews, these are my custom views, i.e. top collection view, a slider).

Please see this screenshot:- https://cloudup.com/cavagxy5-or

Thats why, I divide my functionality in different views which is easy for maintenance purpose in future.

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
@Muhammad-AhmadRafique, everything looks fine, did you try memory analyzer for looking leaks?

**Comment by Muhammad-AhmadRafique** [comment]
Hi @amarunko , Thanks for your response...!
Yes I have checked my project and analyze its code through profiling many times, I will send you the screenshots in a while.
Actually, I am using view(collection of 20 svgViews) at center and a collectionView at the bottom which contains the same view(collection of 20 svgViews),
please see this :- https://cloudup.com/cL54lXYIcdK

So svgs are loaded through filename each time a cell loads and its memory consumption is increased, please see the following screenshots:-

When I come to the above mentioned view and svgs loaded, 
memory consumption :- https://cloudup.com/cwJ8S8dQG9T
When I pop this viewController, memory consumption only reduces to : https://cloudup.com/cAvudVS2h4Y

And after that each time, whenever I come to this ViewController, memory consumption keeps one increasing,

When ViewController pushed:- https://cloudup.com/cS5UJ1x5Pjr
When pop out :- https://cloudup.com/cXhx2Gn-nYV

https://cloudup.com/cCwPRYSJf08
https://cloudup.com/cLaZfU1knD8
https://cloudup.com/ct-ZA3TkSzA
https://cloudup.com/cOOQiaeOwQZ
https://cloudup.com/cysqWR5wEg3

In fact, whenever I pop out my viewController, its memory must be released, but it did not happened.
Please help...!

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
Dear, @Muhammad-AhmadRafique, could you please attach leaks analyzer info? I agree with you - it is leak 100%, I know, that Macaw can have some memory leaks. Exactly analyzer info (classes names which initialize leaked memory, methods where a leak was detected) can help Macaw team resolve this leaks.

To catch this info, you can run "Instruments" from the menu - Xcode -> Open Developer tool -> Instruments -> select "Leaks" and attach to any simulator when a leak is detected - you can export trace info or do the screenshot, thanks.

**Comment by Muhammad-AhmadRafique** [comment]
@amarunko Thanks for your response,
Yes Of course, I was doing the same thing, Please see these screenshots:-

https://cloudup.com/cc3C113JUOq
https://cloudup.com/ciqY8ELvF55
https://cloudup.com/cY3YNDWaUYv

**Macaw Library Memory Leak:-**
https://cloudup.com/cpKB2TlFJOz

Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
@Muhammad-AhmadRafique thanks, I will try to investigate problem deeper

**Comment by amarunko** [comment]
Hi, @Muhammad-AhmadRafique, currently I'm working on this item, we have a memory leak in observers functional, sorry for the inconvenience, I will try to resolve this issue this week.

**Comment by Muhammad-AhmadRafique** [comment]
Thanks @amarunko for your help and coordination.

Kind Regards,
Mohammad Ahmad

**Comment by Muhammad-AhmadRafique** [comment]
Hi @amarunko , Can we move on?
Actually, I have another project in which svgs will be used.?
And this library is awesome, as I already used this one in my previous project.

But I only faced memory issue in it.
Can I integrate it in my new project. ?

Please update me, I need your help.

Thanks,
Kind Regards,
Mohammad Ahmad

**Comment by amarunko** [comment]
Hi, @Muhammad-AhmadRafique, sorry for delays, we are currently working on this item

**Comment by Muhammad-AhmadRafique** [comment]
Thats excellent, 
So, I will wait for your response.

Thanks,

**Comment by mzaatar** [comment]
Hey @amarunko, I'm facing the same issue. any update on this issue? I can spare some time to help.

**Comment by amarunko** [comment]
Hi, @mzaatar, can you attach this file and describe in genera (or prepare small test project) with functional which are you using? It will help a lot.

**Comment by mzaatar** [comment]
Hey @amarunko, I cannot provide the file as it is under NDA for my current project. I'm using the Macaw sample iOS project and tried also the test project from this Medium article: https://medium.com/@cseankurbuet/interaction-of-svg-images-in-your-ios-app-2285566df9a7
In both apps, I got the same error. The file as I can describe it, it is 13k+ lines with hundreds of SVG items.
